### ISSUE TITLE
How can I return error code when I get request body

### ISSUE THREAD

**Issue by RedBlackTreei** [Silvmike/webflux-demo#1]
Thank for your demo, It is great!

I have a question when I use your demo to log request body.

I want to check the params sign in the `LoggingServerHttpRequestDecorator `, but how can I report an error to the client.

 I am a newbie of webflux, so the question may be a bit low-level.

Looking forward to your reply!

**Comment by Silvmike** [comment]
Hello @RedBlackTreei, you can just throw an exception inside a filter, but it requires you to declare an exception handler (org.springframework.web.server.WebExceptionHandler).
See **org.springframework.web.server.handler.FilteringWebHandler** and **org.springframework.web.server.handler.ExceptionHandlingWebHandler**.

You can throw org.springframework.web.server.handler.ResponseStatusException which is handled by **org.springframework.web.server.handler.ResponseStatusExceptionHandler** declared in **org.springframework.web.reactive.config.WebFluxConfigurationSupport** as a bean.

**Comment by Silvmike** [comment]
Hello @RedBlackTreei, sorry for a late reply. 

1. You can throw an exception inside a filter, but it requires you to declare an exception handler (**org.springframework.web.server.WebExceptionHandler**).
See **org.springframework.web.server.handler.FilteringWebHandler** and **org.springframework.web.server.handler.ExceptionHandlingWebHandler**.

You can throw **org.springframework.web.server.handler.ResponseStatusException** which is handled by **org.springframework.web.server.handler.ResponseStatusExceptionHandler** declared in **org.springframework.web.reactive.config.WebFluxConfigurationSupport** as a bean.

2. You can replace the request body with an Flux.error like in **ru.hardcoders.demo.webflux.web_handler.filters.size.MaxPayloadSizeFilter**, and you still need to declare **org.springframework.web.server.WebExceptionHandler**, then spring will do the rest.

3. You can also intercept server exchange processing by not passing it to the chain, and replacing the result. You can just set the response code for the exchange.

There may be other solutions.
